#!/usr/bin/env bash
# shellcheck disable=SC2016
# Requirements:
#    Install nginx on your web-01 server
#    Nginx should be listening on port 80
#    When querying Nginx at its root / with a GET request (requesting a page) using curl, 
#      it must return a page that contains the string Hello World
#    As an answer file, write a Bash script that configures a new Ubuntu machine to
#      respect above requirements (this script will be run on the server itself)
#    You can’t use systemctl for restarting nginx
apt-get update
apt-get install -y nginx
rm -r /var/www/example.com
mkdir -p /var/www/example.com/html
chown -R "$USER":"$USER" /var/www/example.com/html
chmod -R 755 /var/www
touch /var/www/example.com/html/index.html
echo "Hello World" > /var/www/example.com/html/index.html
sed -i 's/location \/ {/location ~ \/redirect_me/$ {/' /etc/nginx/sites-available/default
sed -i 's/try_files $uri $uri\/ =404;/rewrite ^\/redirect_me\/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
sed -i 's/root \/var\/www\/html;/root \/var\/www\/example.com\/html;/' /etc/nginx/sites-available/default
nginx -t
sudo /etc/init.d/nginx restart
